import type { Challenge } from "@/types/challenge";
import { challenge } from "./_builder";

/**
 * Python challenges.
 * Bug line numbers are 1-indexed against the `code` array.
 */
export const PYTHON_CHALLENGES: Challenge[] = [
  // ─── EASY ──────────────────────────────────────────────────────────────
  challenge({
    id: "py-mutable-default-001",
    title: "The Sticky Default",
    filename: "cart.py",
    language: "python",
    difficulty: "easy",
    category: "functions",
    bugType: "incorrect_mutation",
    code: [
      "def add_item(item, items=[]):",
      "    items.append(item)",
      "    return items",
      "",
      "a = add_item('apple')",
      "b = add_item('pear')",
    ],
    bugLines: [1],
    diagnosis: [
      ["A mutable default list is shared across all calls", true],
      ["append() returns None, breaking the return", false],
      ["The function needs a global declaration", false],
    ],
    fixes: [
      ["def add_item(item, items=None):", true],
      ["def add_item(item, items=list):", false],
      ["def add_item(item, *items=[]):", false],
    ],
    explanation:
      "Default arguments are evaluated once at definition time. The same list object is reused across calls, so `b` unexpectedly contains 'apple' too. Use None and create a fresh list inside the body.",
    impact: {
      title: "Data bleeding between requests",
      description: "Shared default lists leaked one user's items into another's.",
      severity: "high",
      metric: "Cross-user data in 220 carts",
    },
    tags: ["mutable-default", "functions", "gotcha"],
  }),
  challenge({
    id: "py-off-by-one-001",
    title: "Index Out Of Range",
    filename: "scan.py",
    language: "python",
    difficulty: "easy",
    category: "loops",
    bugType: "off_by_one",
    code: [
      "def last_three(nums):",
      "    result = []",
      "    for i in range(len(nums) - 2):",
      "        result.append(nums[i])",
      "    return result",
    ],
    bugLines: [3],
    diagnosis: [
      ["range(len - 2) stops two elements early, dropping items", true],
      ["append should be extend", false],
      ["nums[i] raises IndexError", false],
    ],
    fixes: [
      ["    for i in range(len(nums)):", true],
      ["    for i in range(len(nums) + 2):", false],
      ["    for i in range(len(nums) - 1):", false],
    ],
    explanation:
      "range(len(nums) - 2) iterates only up to the third-from-last index, so the last two elements are never appended. Use range(len(nums)) to cover them all.",
    impact: {
      title: "Truncated output",
      description: "Reports silently dropped the two most recent records.",
      severity: "low",
      metric: "Missing rows in daily export",
    },
    tags: ["loops", "range", "off-by-one"],
  }),
  challenge({
    id: "py-none-check-001",
    title: "The None Surprise",
    filename: "profile.py",
    language: "python",
    difficulty: "easy",
    category: "null_handling",
    bugType: "null_reference",
    code: [
      "def display_name(user):",
      "    name = user.get('name')",
      "    return name.upper()",
    ],
    bugLines: [3],
    diagnosis: [
      ["name may be None, and None has no .upper()", true],
      ["user.get should be user.pop", false],
      [".upper() should be .capitalize()", false],
    ],
    fixes: [
      ["    return (name or '').upper()", true],
      ["    return name.upper() or None", false],
      ["    return name.toUpperCase()", false],
    ],
    explanation:
      "dict.get returns None when the key is missing, and calling .upper() on None raises AttributeError. Default to an empty string before calling string methods.",
    impact: {
      title: "AttributeError on profiles",
      description: "Users with no name field crashed the profile renderer.",
      severity: "medium",
      metric: "500 profile errors/day",
    },
    tags: ["none", "dict", "strings"],
  }),
  challenge({
    id: "py-equality-001",
    title: "Is It Really Equal?",
    filename: "compare.py",
    language: "python",
    difficulty: "easy",
    category: "conditions",
    bugType: "wrong_condition",
    code: [
      "def is_admin(role):",
      "    if role is 'admin':",
      "        return True",
      "    return False",
    ],
    bugLines: [2],
    diagnosis: [
      ["`is` compares identity, not value, and may fail for equal strings", true],
      ["The function should return role directly", false],
      ["'admin' must be a bytes literal", false],
    ],
    fixes: [
      ["    if role == 'admin':", true],
      ["    if role = 'admin':", false],
      ["    if role.is('admin'):", false],
    ],
    explanation:
      "`is` checks whether two references point to the same object. String interning makes it seem to work sometimes, but it can return False for equal strings built at runtime. Use == for value comparison.",
    impact: {
      title: "Flaky access checks",
      description: "Admin checks intermittently failed depending on how the role string was built.",
      severity: "medium",
      metric: "Sporadic 403s for admins",
    },
    tags: ["identity", "equality", "strings"],
  }),
  challenge({
    id: "py-integer-div-001",
    title: "Lost In The Rounding",
    filename: "average.py",
    language: "python",
    difficulty: "easy",
    category: "variables",
    bugType: "type_mismatch",
    code: [
      "def average(total, count):",
      "    return total // count",
      "",
      "avg = average(7, 2)",
    ],
    bugLines: [2],
    diagnosis: [
      ["Floor division // truncates the decimal part of the average", true],
      ["count could be zero and crash", false],
      ["total and count are swapped", false],
    ],
    fixes: [
      ["    return total / count", true],
      ["    return total % count", false],
      ["    return int(total / count)", false],
    ],
    explanation:
      "// is floor division, so average(7, 2) returns 3 instead of 3.5. Use / for a true (float) average.",
    impact: {
      title: "Wrong metrics",
      description: "Reported averages were always rounded down, skewing dashboards.",
      severity: "low",
      metric: "Analytics off by up to 1 unit",
    },
    tags: ["division", "numbers", "types"],
  }),

  // ─── MEDIUM ────────────────────────────────────────────────────────────
  challenge({
    id: "py-dict-keyerror-001",
    title: "The Missing Key",
    filename: "settings.py",
    language: "python",
    difficulty: "medium",
    category: "error_handling",
    bugType: "undefined_access",
    code: [
      "def get_timeout(config):",
      "    return config['timeout']",
      "",
      "timeout = get_timeout({'retries': 3})",
    ],
    bugLines: [2],
    diagnosis: [
      ["Indexing a missing key raises KeyError instead of a default", true],
      ["config should be a list", false],
      ["The function needs a return type hint", false],
    ],
    fixes: [
      ["    return config.get('timeout', 30)", true],
      ["    return config['timeout'] or 30", false],
      ["    return config.timeout", false],
    ],
    explanation:
      "config['timeout'] raises KeyError when the key is absent. dict.get with a default returns a safe fallback instead of crashing.",
    impact: {
      title: "Crash on partial config",
      description: "Any config missing 'timeout' took down the worker on startup.",
      severity: "medium",
      metric: "Boot loop on 3 hosts",
    },
    tags: ["dict", "keyerror", "defaults"],
  }),
  challenge({
    id: "py-missing-await-001",
    title: "The Coroutine Never Ran",
    filename: "worker.py",
    language: "python",
    difficulty: "medium",
    category: "async",
    bugType: "missing_await",
    code: [
      "async def process(job):",
      "    data = fetch(job.url)",
      "    save(data)",
      "    return data",
    ],
    bugLines: [2],
    diagnosis: [
      ["fetch() is a coroutine and must be awaited to get its result", true],
      ["save() should be called before fetch()", false],
      ["job.url should be job['url']", false],
    ],
    fixes: [
      ["    data = await fetch(job.url)", true],
      ["    data = fetch.await(job.url)", false],
      ["    data = async fetch(job.url)", false],
    ],
    explanation:
      "Without await, fetch() returns a coroutine object rather than the fetched data. save() then persists the coroutine, and the request never actually runs.",
    impact: {
      title: "Jobs silently no-op",
      description: "Coroutines were saved instead of results; nothing was fetched.",
      severity: "high",
      metric: "9,000 jobs processed empty",
    },
    tags: ["async", "await", "coroutine"],
  }),
  challenge({
    id: "py-late-binding-001",
    title: "The Closure Trap",
    filename: "handlers.py",
    language: "python",
    difficulty: "medium",
    category: "functions",
    bugType: "wrong_condition",
    code: [
      "def make_handlers():",
      "    handlers = []",
      "    for i in range(3):",
      "        handlers.append(lambda: i)",
      "    return handlers",
      "",
      "print([h() for h in make_handlers()])",
    ],
    bugLines: [4],
    diagnosis: [
      ["The lambda captures i by reference, so all return the final value", true],
      ["range(3) should be range(1, 3)", false],
      ["handlers should be a dict", false],
    ],
    fixes: [
      ["        handlers.append(lambda i=i: i)", true],
      ["        handlers.append(lambda: i())", false],
      ["        handlers.append(lambda: return i)", false],
    ],
    explanation:
      "Closures capture the variable, not its value at creation time. By the time the lambdas run, i is 2, so every handler returns 2. Bind the current value with a default argument (lambda i=i: i).",
    impact: {
      title: "All callbacks identical",
      description: "Event handlers all pointed at the last item in the loop.",
      severity: "medium",
      metric: "Wrong row edited 100% of the time",
    },
    tags: ["closures", "late-binding", "lambda"],
  }),
  challenge({
    id: "py-sql-injection-001",
    title: "The Unsafe Lookup",
    filename: "db.py",
    language: "python",
    difficulty: "medium",
    category: "security",
    bugType: "sql_injection",
    code: [
      "def find_user(cursor, username):",
      "    query = \"SELECT * FROM users WHERE name = '%s'\" % username",
      "    cursor.execute(query)",
      "    return cursor.fetchone()",
    ],
    bugLines: [2],
    diagnosis: [
      ["String formatting the username into SQL allows injection", true],
      ["fetchone() should be fetchall()", false],
      ["The query needs a semicolon", false],
    ],
    fixes: [
      ["    cursor.execute('SELECT * FROM users WHERE name = %s', (username,))", true],
      ["    query = \"SELECT * FROM users WHERE name = '\" + username + \"'\"", false],
      ["    cursor.execute(query, username)", false],
    ],
    explanation:
      "Building the query with % string formatting lets an attacker inject SQL. Pass parameters as a tuple to cursor.execute so the driver escapes them.",
    impact: {
      title: "Injectable login",
      description: "A crafted username could bypass auth or read other rows.",
      severity: "critical",
      metric: "Auth bypass demonstrated",
    },
    tags: ["security", "sql", "injection"],
  }),
  challenge({
    id: "py-resource-leak-001",
    title: "The File Left Open",
    filename: "io_utils.py",
    language: "python",
    difficulty: "medium",
    category: "error_handling",
    bugType: "resource_leak",
    code: [
      "def read_config(path):",
      "    f = open(path)",
      "    data = f.read()",
      "    return parse(data)",
    ],
    bugLines: [2],
    diagnosis: [
      ["The file handle is never closed, leaking descriptors", true],
      ["open() needs a mode of 'rb'", false],
      ["parse() should run before read()", false],
    ],
    fixes: [
      ["    with open(path) as f:", true],
      ["    f = open(path); f.close()", false],
      ["    f = open(path, autoclose=True)", false],
    ],
    explanation:
      "If parse() raises (or even on success) the handle is never closed, leaking file descriptors. A `with` block guarantees the file is closed on every exit path.",
    impact: {
      title: "File descriptor exhaustion",
      description: "Long-running workers eventually hit 'too many open files'.",
      severity: "high",
      metric: "Worker crash after ~4h",
    },
    tags: ["resource-leak", "files", "context-manager"],
  }),

  // ─── HARD ──────────────────────────────────────────────────────────────
  challenge({
    id: "py-race-condition-001",
    title: "The Double Spend",
    filename: "wallet.py",
    language: "python",
    difficulty: "hard",
    category: "performance",
    bugType: "race_condition",
    code: [
      "def withdraw(account_id, amount):",
      "    balance = db.get_balance(account_id)",
      "    if balance >= amount:",
      "        db.set_balance(account_id, balance - amount)",
      "        return True",
      "    return False",
    ],
    bugLines: [2],
    diagnosis: [
      ["Read-then-write without a lock lets concurrent withdrawals double-spend", true],
      ["balance should be compared with >", false],
      ["set_balance should take the amount, not the new balance", false],
    ],
    fixes: [
      ["    with db.lock(account_id):  # atomic read-modify-write", true],
      ["    balance = db.get_balance(account_id, fresh=True)", false],
      ["    db.set_balance(account_id, amount - balance)", false],
    ],
    explanation:
      "Two concurrent calls can both read the same balance, both pass the check, and both write — allowing more to be withdrawn than exists. Wrap the read-modify-write in a lock or use an atomic DB update.",
    impact: {
      title: "Money created from nothing",
      description: "Concurrent withdrawals overdrew accounts past zero.",
      severity: "critical",
      metric: "$42K over-withdrawn",
    },
    tags: ["race-condition", "concurrency", "money"],
  }),
  challenge({
    id: "py-float-money-001",
    title: "Pennies From Nowhere",
    filename: "invoice.py",
    language: "python",
    difficulty: "hard",
    category: "variables",
    bugType: "type_mismatch",
    code: [
      "def total_cents(prices):",
      "    total = 0.0",
      "    for p in prices:",
      "        total += p",
      "    return round(total * 100)",
    ],
    bugLines: [2],
    diagnosis: [
      ["Accumulating money as binary floats introduces rounding errors", true],
      ["round() should be floor()", false],
      ["total should start at 1.0", false],
    ],
    fixes: [
      ["    total = Decimal('0')  # use Decimal for money", true],
      ["    total = int(0)", false],
      ["    total = 0.00001", false],
    ],
    explanation:
      "Floats can't represent values like 0.1 exactly, so summing prices drifts by fractions of a cent and round() can land on the wrong integer. Use decimal.Decimal for currency.",
    impact: {
      title: "Invoice totals off by a cent",
      description: "Float rounding produced invoices that failed reconciliation.",
      severity: "high",
      metric: "Ledger mismatch flagged by finance",
    },
    tags: ["float", "decimal", "money"],
  }),
  challenge({
    id: "py-n-plus-one-001",
    title: "The Query Storm",
    filename: "report.py",
    language: "python",
    difficulty: "hard",
    category: "performance",
    bugType: "performance_issue",
    code: [
      "def order_totals(order_ids):",
      "    totals = {}",
      "    for oid in order_ids:",
      "        order = Order.objects.get(id=oid)",
      "        totals[oid] = order.total",
      "    return totals",
    ],
    bugLines: [4],
    diagnosis: [
      ["One query per id creates an N+1 query storm", true],
      ["totals should be a list, not a dict", false],
      [".get() should be .filter()", false],
    ],
    fixes: [
      ["    for order in Order.objects.filter(id__in=order_ids):", true],
      ["    order = Order.objects.get(id=oid, cached=True)", false],
      ["    order = Order.objects.all()[oid]", false],
    ],
    explanation:
      "Calling .get() inside the loop issues a separate query per id. Fetch them all with a single filter(id__in=...) and iterate the result set.",
    impact: {
      title: "Database saturation",
      description: "A 1,000-order report fired 1,000 queries and pinned the DB.",
      severity: "high",
      metric: "DB CPU at 100% during reports",
    },
    tags: ["performance", "orm", "n+1"],
  }),
  challenge({
    id: "py-except-broad-001",
    title: "The Swallowed Error",
    filename: "pipeline.py",
    language: "python",
    difficulty: "hard",
    category: "error_handling",
    bugType: "unhandled_promise",
    code: [
      "def run_step(step):",
      "    try:",
      "        return step.execute()",
      "    except:",
      "        return None",
    ],
    bugLines: [4],
    diagnosis: [
      ["A bare except swallows every error, including KeyboardInterrupt and bugs", true],
      ["step.execute() should be awaited", false],
      ["return None should be return False", false],
    ],
    fixes: [
      ["    except Exception as err:  # catch real errors, log them", true],
      ["    except * :", false],
      ["    except Error:", false],
    ],
    explanation:
      "A bare `except:` catches everything — including SystemExit and KeyboardInterrupt — and silently returns None, hiding real failures. Catch Exception (or a specific type) and log it.",
    impact: {
      title: "Invisible failures",
      description: "Broken pipeline steps returned None and were treated as success.",
      severity: "high",
      metric: "Corrupt output shipped for days",
    },
    tags: ["exceptions", "error-handling", "logging"],
  }),
];
